import cors from 'cors';
import express, { type Express } from 'express';
import helmet from 'helmet';
import { config } from './config/env';
import { errorHandler, notFoundHandler } from './middleware/error-handler';
import { requestLogger } from './middleware/request-logger';
import { createAdminRouter } from './routes/admin.routes';
import { createAuthRouter } from './routes/auth.routes';
import { createCartRouter } from './routes/cart.routes';
import { createCategoriesRouter } from './routes/categories.routes';
import { createHealthRouter } from './routes/health.routes';
import { createOrdersRouter } from './routes/orders.routes';
import { createPaymentsRouter, createStripeWebhookHandler } from './routes/payments.routes';
import { createProductsRouter } from './routes/products.routes';
import { createUsersRouter } from './routes/users.routes';
import { createAppServices } from './services';
import type { AppServices } from './types/services';
import { sendSuccess } from './utils/api-response';
export const createApp = (services?: AppServices): Express => { const resolved = services ?? createAppServices(); const app = express(); app.disable('x-powered-by'); if (config.trustProxy) { app.set('trust proxy', 1); } app.post('/webhook/stripe', express.raw({ type: 'application/json' }), createStripeWebhookHandler(resolved.paymentService)); app.use(helmet()); app.use(cors({ origin: (origin, callback) => { if (!origin || config.corsOrigins.includes(origin)) { callback(null, true); return; } callback(new Error('Origin not allowed by CORS')); }, credentials: true })); app.use(express.json({ limit: '1mb' })); app.use(express.urlencoded({ extended: true })); app.use(requestLogger); app.get('/', (_req, res) => { sendSuccess(res, { data: { name: 'ecommerce-backend', version: '1.0.0' } }); }); app.use('/health', createHealthRouter(resolved.healthService)); app.use('/auth', createAuthRouter(resolved.authService)); app.use('/products', createProductsRouter(resolved.productService)); app.use('/categories', createCategoriesRouter(resolved.categoryService)); app.use('/cart', createCartRouter(resolved.cartService)); app.use('/orders', createOrdersRouter(resolved.orderService)); app.use('/orders', createPaymentsRouter(resolved.paymentService)); app.use('/users', createUsersRouter(resolved.userService)); app.use('/admin', createAdminRouter(resolved.adminService, resolved.orderService, resolved.userService)); app.use(notFoundHandler); app.use(errorHandler); return app; };
