import type { Category, Order, OrderItem, Payment, Product, User } from '../types/entities';

interface UserRow { id: string; email: string; first_name: string; last_name: string; phone: string | null; role: User['role']; is_active: boolean; created_at: Date; updated_at: Date; }
interface CategoryRow { id: string; name: string; description: string | null; image_url: string | null; created_at: Date; updated_at: Date; }
interface ProductRow { id: string; name: string; description: string | null; price: string | number; category_id: string; inventory: number; image_url: string | null; sku: string; is_active: boolean; created_at: Date; updated_at: Date; category_name?: string | null; category_description?: string | null; category_image_url?: string | null; category_created_at?: Date | null; category_updated_at?: Date | null; }
interface PaymentRow { id: string; order_id: string; stripe_payment_intent_id: string | null; amount: string | number; status: Payment['status']; failure_reason: string | null; created_at: Date; updated_at: Date; }
interface OrderRow { id: string; user_id: string; status: Order['status']; total_amount: string | number; shipping_address: Order['shippingAddress']; notes: string | null; created_at: Date; updated_at: Date; }
interface OrderItemRow { id: string; order_id: string; product_id: string; quantity: number; price: string | number; created_at: Date; product_name?: string | null; product_description?: string | null; product_category_id?: string | null; product_inventory?: number | null; product_image_url?: string | null; product_sku?: string | null; product_is_active?: boolean | null; product_created_at?: Date | null; product_updated_at?: Date | null; category_name?: string | null; category_description?: string | null; category_image_url?: string | null; category_created_at?: Date | null; category_updated_at?: Date | null; }
export const toNumber = (value: string | number): number => Number(value);
export const mapUser = (row: UserRow): User => ({ id: row.id, email: row.email, firstName: row.first_name, lastName: row.last_name, phone: row.phone, role: row.role, isActive: row.is_active, createdAt: new Date(row.created_at), updatedAt: new Date(row.updated_at) });
export const mapCategory = (row: CategoryRow): Category => ({ id: row.id, name: row.name, description: row.description, imageUrl: row.image_url, createdAt: new Date(row.created_at), updatedAt: new Date(row.updated_at) });
export const mapProduct = (row: ProductRow): Product => ({ id: row.id, name: row.name, description: row.description, price: toNumber(row.price), categoryId: row.category_id, inventory: row.inventory, imageUrl: row.image_url, sku: row.sku, isActive: row.is_active, createdAt: new Date(row.created_at), updatedAt: new Date(row.updated_at), category: row.category_name && row.category_created_at && row.category_updated_at ? { id: row.category_id, name: row.category_name, description: row.category_description ?? null, imageUrl: row.category_image_url ?? null, createdAt: new Date(row.category_created_at), updatedAt: new Date(row.category_updated_at) } : undefined });
export const mapPayment = (row: PaymentRow): Payment => ({ id: row.id, orderId: row.order_id, stripePaymentIntentId: row.stripe_payment_intent_id, amount: toNumber(row.amount), status: row.status, failureReason: row.failure_reason, createdAt: new Date(row.created_at), updatedAt: new Date(row.updated_at) });
export const mapOrderItem = (row: OrderItemRow): OrderItem => ({ id: row.id, orderId: row.order_id, productId: row.product_id, quantity: row.quantity, price: toNumber(row.price), createdAt: new Date(row.created_at), product: row.product_name && row.product_category_id && row.product_sku && row.product_created_at && row.product_updated_at ? { id: row.product_id, name: row.product_name, description: row.product_description ?? null, price: toNumber(row.price), categoryId: row.product_category_id, inventory: row.product_inventory ?? 0, imageUrl: row.product_image_url ?? null, sku: row.product_sku, isActive: row.product_is_active ?? true, createdAt: new Date(row.product_created_at), updatedAt: new Date(row.product_updated_at), category: row.category_name && row.category_created_at && row.category_updated_at ? { id: row.product_category_id, name: row.category_name, description: row.category_description ?? null, imageUrl: row.category_image_url ?? null, createdAt: new Date(row.category_created_at), updatedAt: new Date(row.category_updated_at) } : undefined } : undefined });
export const mapOrder = (row: OrderRow, items: OrderItem[], payment?: Payment | null): Order => ({ id: row.id, userId: row.user_id, status: row.status, totalAmount: toNumber(row.total_amount), shippingAddress: row.shipping_address, notes: row.notes, createdAt: new Date(row.created_at), updatedAt: new Date(row.updated_at), items, payment: payment ?? null });
