import { NotFoundError, ValidationAppError } from '../errors/AppError';
import type { CartAddItemInput, CartUpdateItemInput } from '../types/api';
import type { Database } from '../types/database';
import type { CartService } from '../types/services';
import type { CartSummary } from '../types/entities';
import { mapProduct, toNumber } from '../utils/mappers';
interface CartRow { id: string; user_id: string; product_id: string; quantity: number; created_at: Date; updated_at: Date; name: string; description: string | null; price: string | number; category_id: string; inventory: number; image_url: string | null; sku: string; is_active: boolean; product_created_at: Date; product_updated_at: Date; category_name: string; category_description: string | null; category_image_url: string | null; category_created_at: Date; category_updated_at: Date; }
interface ProductInventoryRow { id: string; inventory: number; is_active: boolean; }
export class DefaultCartService implements CartService {
  public constructor(private readonly database: Database) {}
  public async getCart(userId: string): Promise<CartSummary> { const result = await this.database.query<CartRow>('SELECT ci.id, ci.user_id, ci.product_id, ci.quantity, ci.created_at, ci.updated_at, p.name, p.description, p.price, p.category_id, p.inventory, p.image_url, p.sku, p.is_active, p.created_at AS product_created_at, p.updated_at AS product_updated_at, c.name AS category_name, c.description AS category_description, c.image_url AS category_image_url, c.created_at AS category_created_at, c.updated_at AS category_updated_at FROM cart_items ci INNER JOIN products p ON p.id = ci.product_id INNER JOIN categories c ON c.id = p.category_id WHERE ci.user_id = $1 AND p.deleted_at IS NULL ORDER BY ci.created_at DESC', [userId]); const items = result.rows.map((row) => { const product = mapProduct({ id: row.product_id, name: row.name, description: row.description, price: row.price, category_id: row.category_id, inventory: row.inventory, image_url: row.image_url, sku: row.sku, is_active: row.is_active, created_at: row.product_created_at, updated_at: row.product_updated_at, category_name: row.category_name, category_description: row.category_description, category_image_url: row.category_image_url, category_created_at: row.category_created_at, category_updated_at: row.category_updated_at }); const subtotal = row.quantity * toNumber(row.price); return { id: row.id, userId: row.user_id, productId: row.product_id, quantity: row.quantity, createdAt: new Date(row.created_at), updatedAt: new Date(row.updated_at), product, subtotal }; }); return { items, total: items.reduce((sum, item) => sum + item.subtotal, 0) }; }
  public async addItem(userId: string, input: CartAddItemInput) { const product = await this.getProductInventory(input.productId); if (!product.is_active) { throw new ValidationAppError('Cannot add inactive products to cart'); } if (input.quantity > product.inventory) { throw new ValidationAppError('Requested quantity exceeds available inventory'); } await this.database.query('INSERT INTO cart_items (user_id, product_id, quantity) VALUES ($1, $2, $3) ON CONFLICT (user_id, product_id) DO UPDATE SET quantity = cart_items.quantity + EXCLUDED.quantity, updated_at = NOW()', [userId, input.productId, input.quantity]); const cart = await this.getCart(userId); const item = cart.items.find((entry) => entry.productId === input.productId); if (item && item.quantity > product.inventory) { throw new ValidationAppError('Requested quantity exceeds available inventory'); } return cart; }
  public async updateItem(userId: string, itemId: string, input: CartUpdateItemInput) { const itemResult = await this.database.query<{ id: string; product_id: string }>('SELECT id, product_id FROM cart_items WHERE id = $1 AND user_id = $2', [itemId, userId]); if (itemResult.rowCount === 0) { throw new NotFoundError('Cart item not found'); } const product = await this.getProductInventory(itemResult.rows[0].product_id); if (input.quantity > product.inventory) { throw new ValidationAppError('Requested quantity exceeds available inventory'); } await this.database.query('UPDATE cart_items SET quantity = $1, updated_at = NOW() WHERE id = $2 AND user_id = $3', [input.quantity, itemId, userId]); return this.getCart(userId); }
  public async removeItem(userId: string, itemId: string) { const result = await this.database.query<{ id: string }>('DELETE FROM cart_items WHERE id = $1 AND user_id = $2 RETURNING id', [itemId, userId]); if (result.rowCount === 0) { throw new NotFoundError('Cart item not found'); } }
  public async clearCart(userId: string) { await this.database.query('DELETE FROM cart_items WHERE user_id = $1', [userId]); }
  private async getProductInventory(productId: string): Promise<ProductInventoryRow> { const result = await this.database.query<ProductInventoryRow>('SELECT id, inventory, is_active FROM products WHERE id = $1 AND deleted_at IS NULL', [productId]); if (result.rowCount === 0) { throw new NotFoundError('Product not found'); } return result.rows[0]; }
}
