import type Stripe from 'stripe';
import { config } from '../config/env';
import { ExternalServiceError, NotFoundError, ValidationAppError } from '../errors/AppError';
import type { ConfirmPaymentInput, CreatePaymentIntentInput } from '../types/api';
import type { Database } from '../types/database';
import type { OrderService, PaymentService } from '../types/services';
import { mapPayment, toNumber } from '../utils/mappers';
interface OrderPaymentRow { id: string; user_id: string; total_amount: string | number; status: 'pending' | 'processing' | 'paid' | 'completed' | 'cancelled'; }
interface PaymentRow { id: string; order_id: string; stripe_payment_intent_id: string | null; amount: string | number; status: 'pending' | 'requires_confirmation' | 'succeeded' | 'failed' | 'cancelled'; failure_reason: string | null; created_at: Date; updated_at: Date; }
const mapStripeIntentStatus = (status: Stripe.PaymentIntent.Status): PaymentRow['status'] => { if (status === 'succeeded') { return 'succeeded'; } if (status === 'requires_confirmation') { return 'requires_confirmation'; } if (status === 'canceled') { return 'cancelled'; } if (status === 'requires_payment_method') { return 'failed'; } return 'pending'; };
export class DefaultPaymentService implements PaymentService {
  public constructor(private readonly database: Database, private readonly stripeClient: Stripe, private readonly orderService: OrderService) {}
  public async createPaymentIntent(userId: string, orderId: string, input: CreatePaymentIntentInput) { const order = await this.getOrderForPayment(orderId, userId); if (!['pending', 'processing'].includes(order.status)) { throw new ValidationAppError('Only pending or processing orders can be paid'); } try { const intent = await this.stripeClient.paymentIntents.create({ amount: Math.round(toNumber(order.total_amount) * 100), currency: config.stripe.currency, payment_method: input.paymentMethodId, metadata: { orderId: order.id, userId: order.user_id }, automatic_payment_methods: { enabled: true } }); await this.database.query('INSERT INTO payments (order_id, stripe_payment_intent_id, amount, status) VALUES ($1, $2, $3, $4) ON CONFLICT (order_id) DO UPDATE SET stripe_payment_intent_id = EXCLUDED.stripe_payment_intent_id, amount = EXCLUDED.amount, status = EXCLUDED.status, updated_at = NOW()', [order.id, intent.id, toNumber(order.total_amount), mapStripeIntentStatus(intent.status)]); return { clientSecret: intent.client_secret, paymentIntentId: intent.id, status: intent.status }; } catch (error) { throw new ExternalServiceError('Failed to create Stripe payment intent', error); } }
  public async confirmPayment(userId: string, orderId: string, input: ConfirmPaymentInput) { await this.getOrderForPayment(orderId, userId); try { const intent = await this.stripeClient.paymentIntents.confirm(input.paymentIntentId); const payment = await this.persistIntentState(orderId, intent); await this.database.query('UPDATE orders SET status = $1, updated_at = NOW() WHERE id = $2', [intent.status === 'succeeded' ? 'paid' : 'processing', orderId]); const order = await this.orderService.getOrderById(orderId, userId, true); return { status: intent.status, order, payment }; } catch (error) { throw new ExternalServiceError('Failed to confirm Stripe payment', error); } }
  public async handleWebhook(signature: string | undefined, payload: Buffer) { if (!signature) { throw new ValidationAppError('Missing Stripe signature header'); } let event: Stripe.Event; try { event = this.stripeClient.webhooks.constructEvent(payload, signature, config.stripe.webhookSecret); } catch (error) { throw new ValidationAppError('Invalid Stripe webhook signature', error); } if (event.type === 'payment_intent.succeeded' || event.type === 'payment_intent.payment_failed') { const intent = event.data.object as Stripe.PaymentIntent; const orderId = intent.metadata.orderId; if (orderId) { const payment = await this.persistIntentState(orderId, intent); await this.database.query('UPDATE orders SET status = $1, updated_at = NOW() WHERE id = $2', [event.type === 'payment_intent.succeeded' ? 'paid' : 'cancelled', orderId]); return { received: true, eventType: `${event.type}:${payment.status}` }; } } return { received: true, eventType: event.type }; }
  private async getOrderForPayment(orderId: string, userId: string): Promise<OrderPaymentRow> { const result = await this.database.query<OrderPaymentRow>('SELECT id, user_id, total_amount, status FROM orders WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL', [orderId, userId]); if (result.rowCount === 0) { throw new NotFoundError('Order not found'); } return result.rows[0]; }
  private async persistIntentState(orderId: string, intent: Stripe.PaymentIntent) { const result = await this.database.query<PaymentRow>('INSERT INTO payments (order_id, stripe_payment_intent_id, amount, status, failure_reason) VALUES ($1, $2, $3, $4, $5) ON CONFLICT (order_id) DO UPDATE SET stripe_payment_intent_id = EXCLUDED.stripe_payment_intent_id, amount = EXCLUDED.amount, status = EXCLUDED.status, failure_reason = EXCLUDED.failure_reason, updated_at = NOW() RETURNING id, order_id, stripe_payment_intent_id, amount, status, failure_reason, created_at, updated_at', [orderId, intent.id, intent.amount / 100, mapStripeIntentStatus(intent.status), intent.last_payment_error?.message ?? null]); return mapPayment(result.rows[0]); }
}
