import { ConflictError, NotFoundError } from '../errors/AppError';
import type { ProductCreateInput, ProductQuery, ProductUpdateInput } from '../types/api';
import type { Database } from '../types/database';
import type { ProductService } from '../types/services';
import { mapProduct } from '../utils/mappers';
import { buildPagination } from '../utils/pagination';
interface ProductRow { id: string; name: string; description: string | null; price: string | number; category_id: string; inventory: number; image_url: string | null; sku: string; is_active: boolean; created_at: Date; updated_at: Date; category_name?: string | null; category_description?: string | null; category_image_url?: string | null; category_created_at?: Date | null; category_updated_at?: Date | null; }
export class DefaultProductService implements ProductService {
  public constructor(private readonly database: Database) {}
  public async listProducts(query: ProductQuery) { const whereClauses = ['p.deleted_at IS NULL']; const values: unknown[] = []; if (query.search) { values.push(`%${query.search}%`); whereClauses.push(`(p.name ILIKE $${values.length} OR COALESCE(p.description, '') ILIKE $${values.length})`); } if (query.categoryId) { values.push(query.categoryId); whereClauses.push(`p.category_id = $${values.length}`); } if (query.minPrice !== undefined) { values.push(query.minPrice); whereClauses.push(`p.price >= $${values.length}`); } if (query.maxPrice !== undefined) { values.push(query.maxPrice); whereClauses.push(`p.price <= $${values.length}`); } if (query.isActive !== undefined) { values.push(query.isActive); whereClauses.push(`p.is_active = $${values.length}`); } const whereSql = whereClauses.join(' AND '); const countResult = await this.database.query<{ total: string }>(`SELECT COUNT(*) AS total FROM products p WHERE ${whereSql}`, values); const offset = (query.page - 1) * query.limit; values.push(query.limit, offset); const rows = await this.database.query<ProductRow>(`SELECT p.id, p.name, p.description, p.price, p.category_id, p.inventory, p.image_url, p.sku, p.is_active, p.created_at, p.updated_at, c.name AS category_name, c.description AS category_description, c.image_url AS category_image_url, c.created_at AS category_created_at, c.updated_at AS category_updated_at FROM products p INNER JOIN categories c ON c.id = p.category_id WHERE ${whereSql} ORDER BY p.created_at DESC LIMIT $${values.length - 1} OFFSET $${values.length}`, values); return { items: rows.rows.map(mapProduct), pagination: buildPagination(query.page, query.limit, Number(countResult.rows[0]?.total ?? 0)) }; }
  public async getProductById(id: string) { const result = await this.database.query<ProductRow>('SELECT p.id, p.name, p.description, p.price, p.category_id, p.inventory, p.image_url, p.sku, p.is_active, p.created_at, p.updated_at, c.name AS category_name, c.description AS category_description, c.image_url AS category_image_url, c.created_at AS category_created_at, c.updated_at AS category_updated_at FROM products p INNER JOIN categories c ON c.id = p.category_id WHERE p.id = $1 AND p.deleted_at IS NULL', [id]); if (result.rowCount === 0) { throw new NotFoundError('Product not found'); } return mapProduct(result.rows[0]); }
  public async createProduct(input: ProductCreateInput) { await this.ensureCategoryExists(input.categoryId); try { const result = await this.database.query<ProductRow>('INSERT INTO products (name, description, price, category_id, inventory, image_url, sku, is_active) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, name, description, price, category_id, inventory, image_url, sku, is_active, created_at, updated_at', [input.name, input.description ?? null, input.price, input.categoryId, input.inventory, input.imageUrl ?? null, input.sku, input.isActive ?? true]); return this.getProductById(result.rows[0].id); } catch (error) { if ((error as { code?: string }).code === '23505') { throw new ConflictError('Product SKU already exists'); } throw error; } }
  public async updateProduct(id: string, input: ProductUpdateInput) { await this.getProductById(id); if (input.categoryId) { await this.ensureCategoryExists(input.categoryId); } const updates: string[] = []; const values: unknown[] = []; const fields: Array<[keyof ProductUpdateInput, string]> = [['name', 'name'], ['description', 'description'], ['price', 'price'], ['categoryId', 'category_id'], ['inventory', 'inventory'], ['imageUrl', 'image_url'], ['sku', 'sku'], ['isActive', 'is_active']]; for (const [field, column] of fields) { const value = input[field]; if (value !== undefined) { values.push(value); updates.push(`${column} = $${values.length}`); } } if (updates.length === 0) { return this.getProductById(id); } values.push(id); try { await this.database.query(`UPDATE products SET ${updates.join(', ')}, updated_at = NOW() WHERE id = $${values.length} AND deleted_at IS NULL`, values); } catch (error) { if ((error as { code?: string }).code === '23505') { throw new ConflictError('Product SKU already exists'); } throw error; } return this.getProductById(id); }
  public async deleteProduct(id: string) { const result = await this.database.query<{ id: string }>('UPDATE products SET deleted_at = NOW(), is_active = FALSE, updated_at = NOW() WHERE id = $1 AND deleted_at IS NULL RETURNING id', [id]); if (result.rowCount === 0) { throw new NotFoundError('Product not found'); } }
  private async ensureCategoryExists(categoryId: string): Promise<void> { const result = await this.database.query<{ id: string }>('SELECT id FROM categories WHERE id = $1 AND deleted_at IS NULL', [categoryId]); if (result.rowCount === 0) { throw new NotFoundError('Category not found'); } }
}
