import type { AdminOrderListQuery, AdminUserListQuery, AuthResult, CartAddItemInput, CartUpdateItemInput, CategoryCreateInput, CategoryUpdateInput, ConfirmPaymentInput, CreateOrderInput, CreatePaymentIntentInput, LoginInput, OrderListQuery, PaginatedResult, ProductCreateInput, ProductQuery, ProductUpdateInput, ProfileUpdateInput, RegisterInput } from './api';
import type { CartSummary, Category, DashboardStats, Order, Payment, Product, User } from './entities';

export interface AuthService { register(input: RegisterInput): Promise<AuthResult>; login(input: LoginInput): Promise<AuthResult>; refreshToken(refreshToken: string): Promise<AuthResult>; }
export interface ProductService { listProducts(query: ProductQuery): Promise<PaginatedResult<Product>>; getProductById(id: string): Promise<Product>; createProduct(input: ProductCreateInput): Promise<Product>; updateProduct(id: string, input: ProductUpdateInput): Promise<Product>; deleteProduct(id: string): Promise<void>; }
export interface CategoryService { listCategories(): Promise<Category[]>; getCategoryById(id: string): Promise<Category>; createCategory(input: CategoryCreateInput): Promise<Category>; updateCategory(id: string, input: CategoryUpdateInput): Promise<Category>; deleteCategory(id: string): Promise<void>; }
export interface CartService { getCart(userId: string): Promise<CartSummary>; addItem(userId: string, input: CartAddItemInput): Promise<CartSummary>; updateItem(userId: string, itemId: string, input: CartUpdateItemInput): Promise<CartSummary>; removeItem(userId: string, itemId: string): Promise<void>; clearCart(userId: string): Promise<void>; }
export interface OrderService { listUserOrders(userId: string, query: OrderListQuery): Promise<PaginatedResult<Order>>; createOrder(userId: string, input: CreateOrderInput): Promise<Order>; getOrderById(orderId: string, userId: string, isAdmin?: boolean): Promise<Order>; updateOrderStatus(orderId: string, status: Order['status']): Promise<Order>; listAllOrders(query: AdminOrderListQuery): Promise<PaginatedResult<Order>>; }
export interface PaymentService { createPaymentIntent(userId: string, orderId: string, input: CreatePaymentIntentInput): Promise<{ clientSecret: string | null; paymentIntentId: string; status: string }>; confirmPayment(userId: string, orderId: string, input: ConfirmPaymentInput): Promise<{ status: string; order: Order; payment: Payment }>; handleWebhook(signature: string | undefined, payload: Buffer): Promise<{ received: boolean; eventType: string }>; }
export interface UserService { getProfile(userId: string): Promise<User>; updateProfile(userId: string, input: ProfileUpdateInput): Promise<User>; getUserById(userId: string): Promise<User>; listUsers(query: AdminUserListQuery): Promise<PaginatedResult<User>>; }
export interface AdminService { getDashboard(): Promise<DashboardStats>; }
export interface HealthService { checkLiveness(): { status: 'ok'; timestamp: string }; checkReadiness(): Promise<{ status: 'ready'; database: 'ok'; timestamp: string }>; }
export interface AppServices { authService: AuthService; productService: ProductService; categoryService: CategoryService; cartService: CartService; orderService: OrderService; paymentService: PaymentService; userService: UserService; adminService: AdminService; healthService: HealthService; }
